// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "Freddie":return img`
.......44.......444.............
......4ee4......4e4.............
.....44ee4.....4ee44............
....44effe4...4eeee44...........
....4eeffee4.44eeee44...........
...4eff11ef444ef11ee44..........
...eeff1eff444fe1f11e4..........
...ff11eeeedddeeeff114..........
...ff1eeeeedddeefeee1e......1...
...ffeeeeee444eeeeeeef......1...
...feeeeeee444eeeeeeef......1f..
...feeeffeeeeeeeffeeef......1f..
...feeeffeeeeeeeffeeef.....14f..
...ffeeeee44444eeeeeff.....eff..
....feeee44fff44eeeef....1efe1..
....feeee44fff44eee8....1e44f...
.....ff8e4444444ee8....f1eeff...
.....ffe8e44444e881e1e4f4e4ff...
.....ffee883f388eeeeee1eefef....
.....ffeeee3f3eeeeeeeeeee4ef....
.....ffeeee333eeeeeeeee14f......
.....ffeeeeeeeeeeeeeeeffff......
.....ff4444444eeffff44ff........
.....ff4444444eeffff44ff........
.....4444....444....4444........
.....4444....444....4444........
................................
................................
................................
................................
................................
................................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
